apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgres://seu_usuario:sua_senha@postgres:5432/seu_banco?sslmode=disable"
  POSTGRES_USER: "seu_usuario"
  POSTGRES_PASSWORD: "sua_senha"
  POSTGRES_DB: "seu_banco"
  MERCADO_PAGO_ACCESS_TOKEN: APP_USR-8119906223498266-051516-0b1dc0cc2f9c6fb392955fb8e20dde55-2444053782
  MERCADO_PAGO_SELLER_APP_USER_ID: "2444053782"
  MERCADO_PAGO_EXTERNAL_POS_ID: DEFAULT
  SECRET_KEY: supersecretkey