
run:
  timeout: 5m
  # Add this to skip Go standard library
linters-settings:
  # rest of your config remains the same
  lll:
    line-length: 140
    tab-width: 4
  revive:
    severity: error
    rules:
      - name: atomic
      - name: context-as-argument
      - name: comment-spacings
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: exported
      - name: receiver-naming
      - name: use-any
      - name: waitgroup-by-value
  stylecheck:
    checks: [ "all", "-ST1000" ]
  staticcheck:
    checks: [ "all" ]
  gosimple:
    checks: [ "all" ]
linters:
  disable-all: true
  enable:
    # Do not ignore errors.
    - errcheck
    - gofmt
    - goimports
    - govet
    # Comments must end with a period.
    - godot
    # No more than 100 characters per line.
    - lll
    - sqlclosecheck
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - gosimple
    - misspell
    - sloglint
issues:
  exclude-dirs:
    - /usr/local/go/
  # Make sure it only checks your project
  exclude-files:
    - main.go
    - ".*\\.pb\\.go$"  # skip protobuf generated files if you have them
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
