services:

  go-web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    networks:
      - db-network
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - db-network
    volumes:
      - ./conf/postgres/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:

networks:
  db-network:
    driver: bridge
