services:
  go-web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - MERCADO_PAGO_ACCESS_TOKEN=${MERCADO_PAGO_ACCESS_TOKEN}
      - MERCADO_PAGO_SELLER_APP_USER_ID=${MERCADO_PAGO_SELLER_APP_USER_ID}
      - MERCADO_PAGO_EXTERNAL_POS_ID=${MERCADO_PAGO_EXTERNAL_POS_ID}
      - UPLOAD_DIR=/app/uploads
      - PUBLIC_URL=${PUBLIC_URL}
      - WEBHOOK_URL=${WEBHOOK_URL}
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - uploads-data:/app/uploads
    networks:
      - db-network
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - db-network
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
  uploads-data:

networks:
  db-network:
    driver: bridge