apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web
  template:
    metadata:
      labels:
        app: go-web
    spec:
      containers:
        - name: go-web
          image: mandacosta/golunch:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_DB
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY
            - name: MERCADO_PAGO_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MERCADO_PAGO_ACCESS_TOKEN
            - name: MERCADO_PAGO_SELLER_APP_USER_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MERCADO_PAGO_SELLER_APP_USER_ID
            - name: MERCADO_PAGO_EXTERNAL_POS_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MERCADO_PAGO_EXTERNAL_POS_ID
            - name: UPLOAD_DIR
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: UPLOAD_DIR
            - name: PUBLIC_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PUBLIC_URL
            - name: WEBHOOK_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: WEBHOOK_URL