apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tech-challenge-fiap161

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - app-deployment.yaml
  - app-service.yaml
  - hpa.yaml

commonLabels:
  project: tech-challenge-fiap161
  version: v1.0.0