apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "goLunch.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: api.golunch.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "goLunch.fullname" . }}
                port:
                  number: 8080
