apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  annotations:
    checksum/db: "{{ .Values.app.db_url | sha256sum }}"
    checksum/user: "{{ .Values.app.db_user | sha256sum }}"
    checksum/password: "{{ .Values.app.db_password | sha256sum }}"
    checksum/mp_token: "{{ .Values.app.mp_access_token | sha256sum }}"
    checksum/mp_seller: "{{ .Values.app.mp_seller_app_user_id | sha256sum }}"
    checksum/secret_key: "{{ .Values.app.secret_key | sha256sum }}"
type: Opaque
stringData:
  DATABASE_URL: "postgres://{{ .Values.app.db_user }}:{{ .Values.app.db_password }}@{{ .Values.app.db_url }}:5432/golunchDB?sslmode=require"
  POSTGRES_USER: "{{ .Values.app.db_user }}"
  POSTGRES_PASSWORD: "{{ .Values.app.db_password }}"
  POSTGRES_DB: "golunchDB"
  MERCADO_PAGO_ACCESS_TOKEN: "{{ .Values.app.mp_access_token }}"
  MERCADO_PAGO_SELLER_APP_USER_ID: "{{ .Values.app.mp_seller_app_user_id }}"
  MERCADO_PAGO_EXTERNAL_POS_ID: DEFAULT
  SECRET_KEY: "{{ .Values.app.secret_key }}"