name: Go CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tests:
    name: Go CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Instalar dependências
        run: go mod tidy

      - name: Rodar testes
        run: go test -v ./...

      - name: Verificar cobertura
        run: go test -cover ./...

      - name: Checar cobertura mínima
        run: |
          go tool cover -func=coverage.out | tee coverage.txt
          total=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          echo "Cobertura total: $total%"
          min=5.0
          below=$(echo "$total < $min" | bc -l)
          if [ $below -eq 1 ]; then
            echo "❌ Cobertura abaixo do mínimo ($min%)"
            exit 1
          fi
